spring:
  rabbitmq:
    host: 192.168.200.132
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true #开启confirm
    publisher-returns: true #开启return
    listener:
      simple:
        acknowledge-mode: manual #开启手动确认模式
        prefetch: 1 #设置拉取消息总量为1