server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka #注册中心地址 如果有多个用逗号分隔
      #http://eureka2:8762/eureka,http://eureka3:8763/eureka
  instance:
    hostname: eureka1 #hosts配置的名称