server:
  port: 9095
spring:
  application:
    name: springcloud-consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka, http://eureka2:8762/eureka #注册中心地址
feign:
  hystrix:
    enabled: true #开启feign熔断器支持
  compression:
    request:
      enabled: true #开启请求压缩
      #以下两个有默认值，可以不配置
      mime-types: text/xml, application/xml, application/json
      min-request-size: 2048 #超过2MB才压缩
    response:
      enabled: true