server:
  port: 9095
spring:
  application:
    name: springcloud-consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka, http://eureka2:8762/eureka #注册中心地址
