server:
  port: 9095
spring:
  application:
    name: springcloud_consumer_service
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka, http://eureka2:8762/eureka #注册中心地址
#修改服务地址轮询策略，默认是轮询，配置之后变随机，RandomRule（IRule）
springcloud_consumer_service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule