server:
  port: 9095
spring:
  application:
    name: springcloud_consumer_service
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka, http://eureka2:8762/eureka #注册中心地址
#修改服务地址轮询策略，默认是轮询，配置之后变随机，RandomRule（IRule）
springcloud_consumer_service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# 配置熔断策略：
hystrix:
  command:
    default:
      circuitBreaker:
        forceOpen: false #强制打开熔断器 默认false关闭的
        requestVolumeThreshold: 20 # 熔断触发最小请求次数，默认值是20
        errorThresholdPercentage: 50 # 触发熔断错误比例阈值，默认值50%
        sleepWindowInMilliseconds: 5000 # 熔断后休眠时长，默认值5秒
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #熔断超时设置，默认为1秒